name: API Test Automation Framework

on:
  workflow_dispatch:  # Enables manual trigger
    inputs:
      testsuite:
        description: 'Select Test Suite'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke
          - regression
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write

    steps:
    
      - uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Execute Tests
        run: mvn clean test -Dgroups=${{ github.event.inputs.testsuite }}

      - name: List files for debugging
        run: ls -R target

      - name: Upload Log file
        if: always()
        uses: actions/upload-artifact@v4.5.0
        with:
          name: Logs
          path: logs/

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            test-output/reports/
            target/surefire-reports/
            logs/

      - name: Publish Extent Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ExtentReport
          path: target/ExtentReport/report.html
          if-no-files-found: warn

      - name: Copy Report to gh-pages Folder
        if: always()

        run: |
          mkdir -p public/extent-reports
          cp -R report.html  public/extent-reports/
          ls -l 

      - name: Deploy 🚀
        if: always()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public/extent-reports/
          token: ${{ secrets.PAT1234 }}
          clean: true   

      # - name: Publish Test Report
      #   if: always()
      #   uses: dorny/test-reporter@v1
      #   with:
      #     name: TestNG Results
      #     path: target/surefire-reports/junitreports/TEST-*.xml
      #     reporter: java-junit
