name: API Test Automation Framework

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven

    - name: Execute Tests
      run: mvn clean test

    - name: Upload ExtentReport HTML
      uses: actions/upload-artifact@v4.5.0
      with:
        name: extent-report
        path: target/ExtentReport/report.html
