name: API Test Automation Framework

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write

    steps:
    
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven

    - name: Execute Tests
      run: mvn clean test

    - name: List report files
      run: ls -R target/

    - name: Upload Log file
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Logs
        path: logs/

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test-output/reports/
          target/surefire-reports/
          logs/
    
    - name: Publish Test Report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: TestNG Results
        path: target/surefire-reports/junitreports/TEST-*.xml
        reporter: java-junit

    - name: Upload HTML Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: target/ExtentReport/report.html

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
      
