name: API Test Automation Framework

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven

    - name: Execute Tests
      run: mvn clean test

    - name: Upload Log file
      if: always()
      uses: actions/upload-artifact@v4.5.0
      with:
        name: Logs
        path: logs/

    # - name: Publish Test Report
    #   if: always()
    #   uses: turing85/publish-report@v2.1.1
    #   with:
    #     name: Extent Report
    #     path: target/ExtentReport/report.html
      
